---
- name: Install common ops tools needed on all servers
  yum:
    name: ['screen', 'telnet', 'deltarpm', 'dos2unix', 'vim', 'zip', 'unzip', 'bzip2', 'gzip', 'patch']
    state: present

- name: Remove git version 1
  yum:
    name: git
    state: removed

- name: Installing epel-release package
  yum:
    name: epel-release
    state: present

- name: Installing IUS repo
  yum:
    name: https://repo.ius.io/ius-release-el7.rpm
    state: present

- name: Install git version 2
  yum:
    name: git2u
    state: present
