---
- name: Install common ops tools needed on all servers
  yum:
    name: ['screen', 'telnet', 'deltarpm', 'dos2unix', 'vim', 'zip', 'unzip', 'bzip2', 'gzip', 'patch', 'wget']
    state: present

- name: get git
  yum:
    name: git
    state: present

- name: Installing epel-release package
  yum:
    name: epel-release
    state: present

- name: Setup project directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ role_user }}"
    group: "{{ role_group }}"
    mode: "{{ item.perm }}"
  loop: "{{ project_dirs }}"
  when: project_dirs is defined
