---
- name: Install common ops tools needed on all servers
  yum:
    name: ['screen', 'telnet', 'deltarpm', 'dos2unix', 'vim', 'zip', 'unzip', 'bzip2', 'gzip', 'patch']
    state: present

- name: Remove git version 1
  yum:
    name: git
    state: removed

- name: Installing epel-release package
  yum:
    name: epel-release
    state: present

- name: Installing IUS repo
  yum:
    name: https://repo.ius.io/ius-release-el7.rpm
    state: present

- name: Install git version 2
  yum:
    name: git2u
    state: present

- name: Setup project directories
  file:
    path: "{{ item.site_dir }}"
    state: directory
    owner: "{{ role_user }}"
    group: "{{ role_group }}"
    mode: '0775'
  loop: "{{ project_dirs }}"

- name: Setup project shared directories
  file:
    path: "{{ item.shared_dir }}"
    state: directory
    owner: "{{ role_user }}"
    group: "{{ role_group }}"
    mode: '0775'
  loop: "{{ project_dirs }}"

- name: Set /srv to role user permissions
  file:
    path: /srv
    state: directory
    recurse: yes
    owner: "{{ role_user }}"
    group: "{{ role_group }}"
    mode: '0775'
